POST http://localhost:8888/CUSTOMER-SERVICE/customers
Content-Type: application/json

{
  "name" : "Zij",
  "email" : "nice"
}

###
POST http://localhost:8086/products
Content-Type: application/json

{
  "name": "food",
  "price": 100.00,
  "quantity": 50
}

###
GET http://localhost:8888/CUSTOMER-SERVICE/customers
Accept: application/json

###

GET http://localhost:8086/products?sort=price,desc&page=0&size=3
Accept: application/json

###
