POST http://localhost:8086/products
Content-Type: application/json

{
  "name": "food",
  "price": 100.00,
  "quantity": 50
}

###
POST http://localhost:8086/products
Content-Type: application/x-www-form-urlencoded

name = food &
price = 100.00 &
quantity = 50

###
GET http://localhost:8086/products/search/findByName?name=food
Accept: application/json

###


